backend_country_index:
    pattern:    /country
    defaults:   { _controller: CountryBundle:Backend:index }
    requirements: { _method: get|head }

backend_country_new:
    pattern:    /country/new
    defaults:   { _controller: CountryBundle:Backend:new }
    requirements: { _method: get|head }

backend_country_create:
    pattern:    /country/new
    defaults:   { _controller: CountryBundle:Backend:create }
    requirements: { _method: post }

backend_country_edit:
    pattern:    /country/edit/{identifier}
    defaults:   { _controller: CountryBundle:Backend:edit }
    requirements: { _method: get|head }

backend_country_update:
    pattern:    /country/edit/{identifier}
    defaults:   { _controller: CountryBundle:Backend:update }
    requirements: { _method: post }

backend_country_delete:
    pattern:    /country/delete/{identifier}
    defaults:   { _controller: CountryBundle:Backend:delete }
    requirements: { _method: get|head }

