backend_country_index:
    pattern:    /
    defaults:   { _controller: Country:Backend:index }
    requirements: { _method: get|head }

backend_country_new:
    pattern:    /new
    defaults:   { _controller: Country:Backend:new }
    requirements: { _method: get|head }

backend_country_create:
    pattern:    /new
    defaults:   { _controller: Country:Backend:create }
    requirements: { _method: post }

backend_country_edit:
    pattern:    /edit/{identifier}
    defaults:   { _controller: Country:Backend:edit }
    requirements: { _method: get|head }

backend_country_update:
    pattern:    /edit/{identifier}
    defaults:   { _controller: Country:Backend:update }
    requirements: { _method: post }

backend_country_delete:
    pattern:    /delete/{identifier}
    defaults:   { _controller: Country:Backend:delete }
    requirements: { _method: get|head }

